# Generated by Django 4.2.19 on 2025-03-10 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Firma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=255, unique=True)),
                ("adres", models.TextField(blank=True, null=True)),
                ("telefon", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Musteri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad_soyad", models.CharField(max_length=255)),
                ("telefon", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("adres", models.TextField(blank=True, null=True)),
                ("eklenme_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "firma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="musteriler",
                        to="stok_app.firma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("can_manage_critical_stock", models.BooleanField(default=False)),
                ("can_add_product", models.BooleanField(default=True)),
                ("can_edit_product", models.BooleanField(default=True)),
                ("can_delete_product", models.BooleanField(default=True)),
                (
                    "firma",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stok_app.firma",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Urun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=100)),
                ("kategori", models.CharField(max_length=50)),
                ("stok_miktari", models.IntegerField()),
                (
                    "birim",
                    models.CharField(
                        choices=[
                            ("adet", "Adet"),
                            ("kg", "Kilogram"),
                            ("m", "Metre"),
                            ("lt", "Litre"),
                            ("kutu", "Kutu"),
                        ],
                        default="adet",
                        max_length=10,
                    ),
                ),
                ("fiyat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tarih", models.DateTimeField(auto_now_add=True)),
                ("kritik_stok", models.PositiveIntegerField(default=5)),
                ("son_kritik_stok_tarihi", models.DateTimeField(blank=True, null=True)),
                (
                    "firma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stok_app.firma",
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Satis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("satis_adedi", models.PositiveIntegerField()),
                ("satis_fiyati", models.DecimalField(decimal_places=2, max_digits=10)),
                ("satis_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "firma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stok_app.firma",
                    ),
                ),
                (
                    "musteri",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stok_app.musteri",
                    ),
                ),
                (
                    "satis_yapan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "urun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stok_app.urun"
                    ),
                ),
            ],
        ),
    ]
