# Generated by Django 4.2.19 on 2025-03-13 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stok_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("ÜRÜN", "Ürün İşlemi"),
                            ("SATIŞ", "Satış İşlemi"),
                            ("STOK", "Stok Güncelleme"),
                            ("GENEL", "Genel İşlem"),
                        ],
                        max_length=20,
                    ),
                ),
                ("mesaj", models.TextField()),
                ("tarih", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "firma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stok_app.firma",
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
