# Generated by Django 4.2.19 on 2025-03-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stok_app", "0002_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="urun",
            name="barkod",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
