# Generated by Django 4.2.19 on 2025-03-21 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("stok_app", "0003_urun_barkod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="satis",
            name="satis_tarihi",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
